CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_google VARCHAR(128) NOT NULL UNIQUE KEY,
    username1 VARCHAR(128) DEFAULT 'user1',
    username2 VARCHAR(128) DEFAULT 'user2',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP()
)