CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id_google VARCHAR(128) UNIQUE KEY,
    username1 VARCHAR(128),
    username2 VARCHAR(128),
    email VARCHAR(128),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP()
)